### ISSUE TITLE
Add missing data to releases

### ISSUE THREAD

**Issue by ronoc** [ronoc/forwind.net#52]
- [ ] mastering
- [ ] producer
- [ ] artwork
- [ ] chosen quote

**Comment by Shane-Forwind** [comment]
FWD00
Graham Semark
Conor Curran
Paul Finn
Form is a retrospective of the CJC output between 2000 & 2003. Spacial geometric concepts act as the origins of the timbre and expression within this found-sound digital work. 

CJC’s ‘Elastics’ with its clattering watery drums and fuzzy noises backed by poignant melodies and lush strings to build a superb track of trademark electronics. - Boomkat

**Comment by Shane-Forwind** [comment]
FWD01
Graham Semark
Conor Curran
Fitzroy & Flynn
Seven Months In E Minor is a record which unveils its profound beauty with great care, and requires a level of commitment to fully appreciate its depth. - themilkfactory

Or 

The deep level of understanding between the two musicians makes it a wonderfully enjoyable record. - themilkfactory

**Comment by Shane-Forwind** [comment]
FWD02
Mark Beazley
James O’Sullivan
Alexandra Hobson
O'Sullivan manages to produce rich and varied music… that handsomely repays the time invested in listening to it -  John Eyles - All About Jazz

**Comment by Shane-Forwind** [comment]
FWD03
Jon Clayton
Ian R. Watson, Peter Marsh, Paul May
Peter Marsh
The album reveals Elvers to have its own well-defined identity and sound…making it a group to watch. -  John Eyles - All About Jazz

**Comment by Shane-Forwind** [comment]
FWD04
Graham Semark
Conor Curran 
Riccardo Arena
There is something exhilarating about this modest yet perverse album and its refusal to conform. - Clive Bell - The Wire

**Comment by Shane-Forwind** [comment]
FWD05
Ben Turner
Charlie Beresford
Charlie Beresford
I thought it was perhaps the sort of song cycle Schubert might have written if he’d been around today. - Fiona Talkington, Late Junction, BBC Radio 3

**Comment by Shane-Forwind** [comment]
FWD06
Conor Curran 
Conor Curran 
Maura Curran
Sonnamble’s approach is an intellectual one…yet these ambient, floating minimalist soundscapes still have the ability to emote…Wyndham Wallace - BBC Music

**Comment by Shane-Forwind** [comment]
FWD07
Patrick Fennelly, Cian Walker, Jason Joomun
Conor Curran
Anne Grön
The trio has done well to exercise restraint…they imitate the best directors, who create tension without resorting to shock… - Richard Allen - A Closer Listen

**Comment by Shane-Forwind** [comment]
FWD08
Charlie Beresford
Charlie Beresford
Hannes Jentsch
The group blend elements of jazz, folk, classical and ambient music in a uniquely contemporary manner… - Ian Mann - The Jazz Mann

Or

Fourth Page seem to have discovered a whole new vocabulary… that sets them apart from the improv establishment. - Ian Mann - The Jazz Mann

**Comment by Shane-Forwind** [comment]
FWD10
Jeff Carey
Jeff Carey
Hannes Jentsch
Jeff has forged a signature sound. I haven’t hear anything quite like it. - Guttermag

**Comment by Shane-Forwind** [comment]
FWD11
James Aparicio
Elsie Martins, James Aparicio
Oliver Barton
Elsie Martins’ enthusiasm for her medium is addictive. There’s something phantom-like about her music – a sense of suspension and unresolve... - ATTN:MAGAZINE

**Comment by Shane-Forwind** [comment]
FWD12
Denis Blackham
Tomonari Nozaki 
Jakob Brondum
On the surface, this is ambient music, but with a more intricate lattice than one might observe at softer volumes. - Richard Allen - A Closer Listen

**Comment by Shane-Forwind** [comment]
FWD13
Denis Blackham
Tomonari Nozaki
Jakob Brondum
“Pt. 2” of “Decadence” is most likely my favourite track of the whole trilogy...in the final conclusion it’s all swept away by the rumbling sound of the wasteland echoes. - Santa Sangre

**Comment by Shane-Forwind** [comment]
FWD15
Rutger Zuydervelt, Philippe Petit
Rutger Zuydervelt, Philippe Petit
British Library archive
Angry Ambient Artists is a reaction to the label, akin to turning a rock and finding worms underneath...but “Graniet” is still accidentally gorgeous. - Richard Allen - A Closer Listen

**Comment by Shane-Forwind** [comment]
FWD16 
Conor Curran
Svetlana Maraš, George Royle
British Library archive
Angry Ambient Artists Vol. 2 has plenty of “oomph,” but its violent fuzz is able to masquerade as soothing drone. This is a lullaby of the worst kind. - Sly Vinyl

Or

One starts to wonder if any voice could be understood above the noise, a metaphor for these dissonant times. - Richard Allen - A Closer Listen

**Comment by Shane-Forwind** [comment]
FWD17
Denis Blackham, Conor Curran
Tomonari Nozaki 
Jakob Brondum
The man needs to be given a film to match the scope of his cinematic music right now. Stunning music. - Richard Johnson - Adverse Effect 

Or

This stunning EP series is tied together thematically by the art of Jakob Brondum.  His swirling paints produce a sense of synaesthesia that is reflected in the music. - Richard Allen - A Closer Listen

Or

The whole is re-imagined into a dish fit to set before Basinski buffs and Hecker checkers. The series’ sheer sweep sees Nozaki’s sound gather in sono-dramatic force, cementing detail, texture and integration of its parts. Alan Lockett - Igloo Magazine

**Comment by Shane-Forwind** [comment]
FWD18
Conor Curran
Linus Schrab, Johan Fotmeijer
Hannes Jentsch
Schrab and Fotmeijer’s dark offering characterizes a set of uneasy emotions that are felt not only in the Rust Belt, but anywhere that industry is in decline. - Avant Music News

Or

There’s a balance across the 39-minute album between ambience and percussion that results in an appropriately combined sense of loss and genuine angst. - Kevin Press - Badd Press Blog

**Comment by Shane-Forwind** [comment]
FWD19
Conor Curran
Jeremy Keenan
Martina O'Shea 
Scripts features four deeply satisfying pieces. Music in this genre doesn’t often inspire listeners to turn the volume knob clockwise. This one absolutely does. - Kevin Press - Badd Press Blog

**Comment by Shane-Forwind** [comment]
FWD20
Conor Curran, Dieter Kovacic
Childe Grangier, Gabriel Ghebrezghi, Billy Roisz
British Library archive
It is less a response to the mainstream of ambient music than it is a part of where the real action is...These recordings are all imaginative and beautifully produced. - Kevin Press - Badd Press Blog
