### ISSUE TITLE
Implement 'pop out artwork feature' on releases

### ISSUE THREAD

**Issue by ronoc** [ronoc/forwind.net#55]
[releases_mobile_003_vis_des_005_lightbox copy.pdf](https://github.com/ronoc/forwind.net/files/1910528/releases_mobile_003_vis_des_005_lightbox.copy.pdf)

**Comment by ramonjd** [comment]
https://github.com/ronoc/forwind.net/commit/0389ea428ba5a37c9ba6745656b48ace31dfeccc
